spring:
  application:
    name: search-module-api
  profiles:
    include:
      - data
server:
  port: 4000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  shutdown: graceful

logging:
  level:
    com: DEBUG
app:
  api:
    kakao:
      url: "https://dapi.kakao.com"
      key: "KakaoAK d4e6fbfeb0c1dfbf800646b0ddd3f49a"
    naver:
      url: "https://openapi.naver.com"
      clientId: "lPXdEZfpMIvgZJB1UfX7"
      clientSecret: "Ucle4yj6uc"
feign:
  circuitbreaker:
    enabled: true
  httpclient:
    disableSslValidation: true
  client:
    config:
      default:
        connect-timeout: 30000
        read-timeout: 30000
        loggerLevel: FULL