spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:search;MODE=MYSQL
    username: user
    password:
    hikari:
      connection-timeout: 100000
      maximum-pool-size: 100
  jpa:
    database: h2
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
