INSERT INTO SEARCH_WORD VALUES
(NULL, 'keyword_1', 1),
(NULL, 'keyword_2', 2),
(NULL, 'keyword_3', 3),
(NULL, 'keyword_4', 4),
(NULL, 'keyword_5', 5),
(NULL, 'keyword_6', 6),
(NULL, 'keyword_7', 7),
(NULL, 'keyword_8', 8),
(NULL, 'keyword_9', 9),
(NULL, 'keyword_10', 10),
(NULL, 'keyword_11', 11),
(NULL, 'keyword_12', 12),
(NULL, 'keyword_13', 1),
(NULL, 'keyword_14', 1),
(NULL, 'keyword_15', 1);